name: ClanPlugin
version: ${project.version}
main: me.harambe_hotsauce.clans.ClanPlugin
api-version: 1.13
authors: [Harambe_Hotsauce]
description: Create and join clans with you friends!
commands:
  clans:
    description: general commmand for clan plugin
    usage: /clans [create, info, addslots, list, delete, invite, leave, kick, setprefix] [clan]
    permission: clan.basic
    permission-message: You don't have <permission>
  opclans:
    description: commands used by operators for management purposes
    usage: /clans [changeleader, disband, setprefix, removemember] [clan]
    permission: clan.op
    permission-message: You don't have <permission>